[pytest]
addopts = -l --strict --ignore=substanced/scaffolds
norecursedirs = lib include .tox .git
python_files = test_*.py
filterwarnings =
     ignore::DeprecationWarning:ast
     ignore::DeprecationWarning:chameleon
     ignore::DeprecationWarning:hypatia
     ignore::DeprecationWarning:webob
     ignore::DeprecationWarning:zodburi
     ignore:pkg_resources is deprecated as an API:DeprecationWarning:
     ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning:
